import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "@/src/styles/globals.css";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"], // Include arabic for proper Cairo usage
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"], // Add weights you actually need
});

export const metadata: Metadata = {
  title: "Platme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.variable}`}>
        <div className="flex flex-col pt-8 h-screen bg-[#f2f2f2] w-screen">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
